### ISSUE TITLE
Issue running samples

### ISSUE THREAD

**Issue by DamienDoumer** [ttustonic/GStreamerSharpSamples#2]
I'm trying to run Gstreamer-Sharp on windows. I downloaded the source code from github and tried running samples. I followed this installation guide and added environment variables as required. But When I run Gstreamer, I get this exception:

Exception thrown: 'System.DllNotFoundException' in gstreamer-sharp.dll An unhandled exception of type 'System.DllNotFoundException' occurred in gstreamer-sharp.dll Unable to load DLL 'gstapp-1.0-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

This exception occures when initializing the library at

GLib.GType.Register (Gst.App.AppSink.GType, typeof (Gst.App.AppSink));

Please any info about how to resolve it ?

**Comment by ttustonic** [comment]
Are you using Gstreamer 1.16?
Samples are written with GStreamer 1.14.x. Version 1.16 is compiled with MS C compiler, which generates different dll file names (old name libgstapp-.. , new name gstapp-...). Try with the older version of GStreamer. 
It will probably be fixed with version 1.18 of GStreamer, see 
[https://gitlab.freedesktop.org/gstreamer/gstreamer-sharp/issues/26](https://gitlab.freedesktop.org/gstreamer/gstreamer-sharp/issues/26)

**Comment by DamienDoumer** [comment]
Hello,
I was using version 1.6.
Thanks for the advice, I'll use v 1.4 then.

Best Regards,
Damien Doumer
https://doumer.me

Le mar. 11 févr. 2020 à 22:43, ttustonic <notifications@github.com> a
écrit :

**Comment by DamienDoumer** [comment]
Hello,  Please after installing thisgstreamer-1.0-x86-1.4.5.msiOn Windows and adding the path: “C:\gstreamer\1.0\x86_64\bin”  To my project’s properties in the field “working directory” as stated in the gstreamer installation guide, I still get the error: An unhandled exception of type 'System.DllNotFoundException' occurred in gstreamer-sharp.dllFor the library with name: “gstapp-1.0-0.dll”When I change the library’s name to “libgstapp-1.0-0.dll” in the [dll import], I still get an error stating “Exception thrown: 'System.BadImageFormatException' in gstreamer-sharp.dll”Please can someone help ?. Best Regards,Damien Doumer T.Khttps://doumer.me From: ttustonicSent: Tuesday, February 11, 2020 10:43 PMTo: ttustonic/GStreamerSharpSamplesCc: Damien Doumer; AuthorSubject: Re: [ttustonic/GStreamerSharpSamples] Issue running samples (#2) Are you using Gstreamer 1.16?Samples are written with GStreamer 1.14.x. Version 1.16 is compiled with MS C compiler, which generates different dll file names (old name libgstapp-.. , new name gstapp-...). Try with the older version of GStreamer.It will probably be fixed with version 1.18 of GStreamer, seehttps://gitlab.freedesktop.org/gstreamer/gstreamer-sharp/issues/26—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DamienDoumer** [comment]
Hi, Please after installing this
gstreamer-1.0-x86-1.4.5.msi

On Windows and adding the path: “C:\gstreamer\1.0\x86_64\bin”  
To my project’s properties in the field “working directory” as stated in the gstreamer installation guide, I still get the error: 
An unhandled exception of type 'System.DllNotFoundException' occurred in gstreamer-sharp.dll
For the library with name: “gstapp-1.0-0.dll”
When I change the library’s name to “libgstapp-1.0-0.dll” in the [dll import], I still get an error stating “Exception thrown: 'System.BadImageFormatException' in gstreamer-sharp.dll” 
Please do you have any idea about what to do ?
Sorry but I really don't know in which forum I can find help about Gstreamer-sharp reason why I opened this issue.

**Comment by ttustonic** [comment]
Hm, you seem to be mixing something. 
`BadImageFormatException` occurs when trying to load 64bit dll in 32bit application. All the projects target x86 platform. Are you using 32-bit or 64-bit gstreamer installation?
Also, you should use older version of `gstreamer-sharp `nuget package (1.14 or something), or use the `gstreamer-sharp` project which is in the samples. There's no need to change dllimport anywhere. If you want to compile gstreamer-sharp, use older branch.
You might also add your gstreamer bin (and possibly lib) installation directory to the PATH environment variable.
I just installer `gstreamer-1.0-x86-1.14.5.msi` and `gstreamer-1.0-devel-x86-1.14.5` (this is probably not needed for the samples, but just in case), and `BasicTutorial01 `works fine.

**Comment by DamienDoumer** [comment]
Hi, thanks. I was installing the 64 bits version and targeted my project to 64bits too... But when I downloaded version 1.14 x86 I stopped having those errors... thanks I think that behavior is weird.

**Comment by Raj123456788** [comment]
Hello, I followed your steps above to install the gstreamer-1.0-x86-1.14.5.msi and gstreamer-1.0-devel-x86-1.14.5 I can see the libgstreamer-1.0-0.dll in C:\gstreamer\1.0\x86\bin so I set the enviornmental variable to this path. Please can you help me as to why I am seeing thios error?
![image](https://user-images.githubusercontent.com/16295521/89822157-98e94d00-db04-11ea-8185-9f9da0c1e5f1.png)

**Comment by ttustonic** [comment]
Hello
You are probably missing `GSTREAMER_ROOT_X86` environment variable. It should be `C:\gstreamer\1.0\x86\`
If you use 64bit version you'll need `GSTREAMER_ROOT_X86_64`

**Comment by Raj123456788** [comment]
hey, I have this GSTREAMER_ROOT_X86   as my system enviornmental variable. I have 64bit machine  and I am running WinformSample. I have been trying running different github repos and none of them are working for since 2 days

**Comment by Raj123456788** [comment]
I have also added GST_PLUGIN_PATH & GST_PLUGIN_SYSTEM_PATH to C:\gstreamer\1.0\x86\bin

**Comment by Raj123456788** [comment]
Do I need to run gstreamer-1.0-x86-1.14.5.msi and gstreamer-1.0-devel-x86-1.14.5. 64 bit versions of these installers?

**Comment by ttustonic** [comment]
Hm, sorry, it's been years since I played with GStreamer. I don't have it installed anymore.
However, it should work with 32bit version of GStreamer. I tested it on Feb 13 and it worked.
Probably stupid question, but did you restart Visual studio after installing GStreamer and setting Path and environment variables?

**Comment by Raj123456788** [comment]
yes I did restart my VS. I am trying 64bit installer now. Can you tell me what system variables I need to have. I knowhttps://gstreamer.freedesktop.org/documentation/installing/on-windows.html?gi-language=c  says GST_PLUGIN_PATH and GSTREAMER_ROOT and thing else? exact values as well

**Comment by ttustonic** [comment]
`GSTREAMER_ROOT_X86 `should point to the root of your 32bit installation, for example `C:\gstreamer\1.0\x86\`
`GSTREAMER_ROOT_X86_64` should point to the root of your 64bit installation, for example `C:\gstreamer\1.0\x86_64\`

You can also try setting `GSTREAMER_1_0_ROOT_X86` and `GSTREAMER_1_0_ROOT_X86_64` using same values as above.

Default installation should work without setting `GST_PLUGIN_PATH`.

Also, check that your environment variables don't include /bin folder, but your Path does, so your Path should include `%GSTREAMER_ROOT_X86%\bin` (environment variable is automatically expanded).

**Comment by Raj123456788** [comment]
The path variable in the enviornmental variables need to have the C:\gstreamer\1.0\x86_64\bin. That worked: also for x64 it need to allow the unsafe code checkbox checked.

**Comment by zemskymax** [comment]
Hi,
I have downloaded the repository and installed the gstreamer (by running the gstreamer-1.0-x86-1.14.5.msi and the gstreamer-1.0-devel-x86-1.14.5). Also, I have checked the environment variables - everything looks OK.

Running the WpfExamples project I get the following exception:
Managed Debugging Assistant 'PInvokeStackImbalance' 
 Message=Managed Debugging Assistant 'PInvokeStackImbalance' : 'A call to PInvoke function 'GLibSharp!GLib.Marshaller+d_g_malloc::Invoke' has unbalanced the stack. 
 This is likely because the managed PInvoke signature does not match the unmanaged target signature. 
 Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'

What am I missing?

Thanks!
